# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: xs000_GAN_DSCAM-ST_0.3
model_type: DASR_GAN_bic_Model
scale: 4
num_gpu: 8
manual_seed: 10

l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False

degree_list: ['weak_degrade_one_stage', 'standard_degrade_one_stage', 'severe_degrade_two_stage']
degree_prob: [0.3,0.3,0.4]

# the degradation process of weak_degrade_one_stage
resize_prob_weak1: [0.1, 0.2, 0.7]  # up, down, keep
resize_range_weak1: [0.85, 1.2]
gaussian_noise_prob_weak1: 0.5
noise_range_weak1: [1, 10]
poisson_scale_range_weak1: [0.05, 0.5]
gray_noise_prob_weak1: 0.4
jpeg_range_weak1: [90, 95]

# the degradation process of standard_degrade_one_stage
resize_prob_standard1: [0.3, 0.4, 0.3]  # up, down, keep
resize_range_standard1: [0.5, 1.2]
gaussian_noise_prob_standard1: 0.5
noise_range_standard1: [1, 20]
poisson_scale_range_standard1: [0.05, 1.5]
gray_noise_prob_standard1: 0.4
jpeg_range_standard1: [50, 95]

# the first degradation process of severe_degrade_two_stage
resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
resize_range: [0.15, 1.5]
gaussian_noise_prob: 0.5
noise_range: [1, 30]
poisson_scale_range: [0.05, 3]
gray_noise_prob: 0.4
jpeg_range: [30, 95]

# the second degradation process of severe_degrade_two_stage
second_blur_prob: 0.8
resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
resize_range2: [0.3, 1.2]
gaussian_noise_prob2: 0.5
noise_range2: [1, 25]
poisson_scale_range2: [0.05, 2.5]
gray_noise_prob2: 0.4
jpeg_range2: [30, 95]

gt_size: 256
queue_size: 192


# dataset and data loader settings
datasets:
  train:
    name: Holopix50k_train
    type: DASR_Dataset
    dataroot_gt: /lxy/Holopix50k/train/patches_hr_Holopix50k_
    #meta_info: /lxy/meta_info_validation_HR_sub.txt
    io_backend:
      type: disk

    blur_kernel_size_weak1: 21
    blur_kernel_size_minimum_weak1: 7
    kernel_list_weak1: [ 'iso', 'aniso' ]
    kernel_prob_weak1: [ 0.65, 0.35 ]
    sinc_prob_weak1: 0
    blur_sigma_weak1: [ 0.2, 0.8 ]
    betag_range_weak1: [ 0.5, 4 ]
    betap_range_weak1: [ 1, 2 ]

    blur_kernel_size_standard1: 21
    blur_kernel_size_minimum_standard1: 7
    kernel_list_standard1: [ 'iso', 'aniso' ]
    kernel_prob_standard1: [ 0.65, 0.35 ]
    sinc_prob_standard1: 0
    blur_sigma_standard1: [ 0.2, 1.5 ]
    betag_range_standard1: [ 0.5, 4 ]
    betap_range_standard1: [ 1, 2 ]

    blur_kernel_size: 21
    blur_kernel_size_minimum: 7
    kernel_list: [ 'iso', 'aniso']
    kernel_prob: [ 0.65, 0.35]
    sinc_prob: 0
    blur_sigma: [0.2, 3]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 21
    blur_kernel_size2_minimum: 7
    kernel_list2: [ 'iso', 'aniso' ]
    kernel_prob2: [ 0.65, 0.35 ]
    sinc_prob2: 0
    blur_sigma2: [0.2, 1.5]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.8


    gt_size_h: 256
    gt_size_w: 256
    use_hflip: true
    use_vflip: true
    use_rot: true
    flip_RGB: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val0:
    name: holopix50k_val_level1
    type: PairedImageSRLRDataset_
    dataroot_gt: /lxy/Holopix50k/holopix_100/hr
    dataroot_lq: /lxy/Holopix50k/_holopix_level1_100
    io_backend:
      type: disk

  val1:
    name: holopix50k_val_level2
    type: PairedImageSRLRDataset_
    dataroot_gt: /lxy/Holopix50k/holopix_100/hr
    dataroot_lq: /lxy/Holopix50k/_holopix_level2_100
    io_backend:
      type: disk

  val2:
    name: holopix50k_val_bic
    type: PairedImageSRLRDataset_
    dataroot_gt: /lxy/Holopix50k/holopix_100/hr
    dataroot_lq: /lxy/Holopix50k/holopix_100/holopix_bicx4
    io_backend:
      type: disk

  val3:
    name: Flickr1024_val
    type: PairedImageSRLRDataset
    dataroot_gt: /lxy/datasets/stereo/Val/Validation
    dataroot_lq: /lxy/datasets/stereo/Val/LR_x4
    io_backend:
      type: disk

# network structures
network_g:
  type: STSSR_MSCAM
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 8
  overlap_ratio: 0.3
  img_range: 1.0
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'nearest+conv'
  resi_connection: '1conv'
  train_size: [1, 6, 64, 64]
  dual: true
  fusion: true

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True

# path
path:
  pretrain_network_g: /lxy/STSSR/basicsr/test/swinir/003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_GAN.pth
  # param_key_g: params_ema
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [400000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  # gan loss
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  trans_num: 1

  max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    # ssim:
    #   type: calculate_skimage_ssim
    # ssim: # metric name, can be arbitrary
    #   type: calculate_ssim
    #   crop_border: 0
    #   test_y_channel: false

    lpips:
      type: calculate_lpips
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
